### ISSUE TITLE
Got error when install (node v6.9.1 | windows x86)

### ISSUE THREAD

**Issue by sheeeeep** [maxogden/rabin#16]
```
$ npm i rabin --save-dev
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g

> rabin@1.5.0 install E:\Minwise Hash\node_modules\rabin
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v6.9.1 arch=x64 platform=win32)
prebuild ERR! configure error
prebuild ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! stack     at failNoPython (E:\Minwise Hash\node_modules\node-gyp\lib\configure.js:449:14)
prebuild ERR! stack     at E:\Minwise Hash\node_modules\node-gyp\lib\configure.js:404:11
prebuild ERR! stack     at E:\Minwise Hash\node_modules\graceful-fs\polyfills.js:276:29
prebuild ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
prebuild ERR! not ok
prebuild ERR! build Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! build     at failNoPython (E:\Minwise Hash\node_modules\node-gyp\lib\configure.js:449:14)
prebuild ERR! build     at E:\Minwise Hash\node_modules\node-gyp\lib\configure.js:404:11
prebuild ERR! build     at E:\Minwise Hash\node_modules\graceful-fs\polyfills.js:276:29
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN minwise-hash@1.0.0 No description
npm WARN minwise-hash@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "rabin" "--save-dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! rabin@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the rabin@1.5.0 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rabin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rabin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rabin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Minwise Hash\npm-debug.log
```

**Comment by max-mapper** [comment]
+1

**Comment by joehand** [comment]
Another windows install error: 

```
target=v4.4.0 arch=x64 platform=win32
```

**Comment by juliangruber** [comment]
can you try again, with the latest version? rabin now has prebuilds for windows 32/64 bit too

**Comment by Xmader** [comment]
the only thing you need to do is to install Python.
