### ISSUE TITLE
Enhancement request: expose chunk_cut_fingerprint in JS out stream object

### ISSUE THREAD

**Issue by green-coder** [maxogden/rabin#4]
`chunk_cut_fingerprint` is not only useful inside the low level splitting algorithm. It can also be used by the JS program to group the sha256 hashes by using the upper bits (above the 14th bit) as delimiters. The idea is to have a merkel tree with a depth higher than 2, this is very needed for handling large files (1~2 GB).

I would be happy to implement the change myself, but I do not master the build process for C bind yet.

**Comment by green-coder** [comment]
I tried to compile the module with `node-gyp configure` and I got this error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:435:26)
    at node.js:576:27
    at doNTCallback0 (node.js:417:9)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /Users/Vincent/Moulin/pro/playerium/rabin
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
```

**Comment by green-coder** [comment]
To be more precise, the information I request is only the number of low weight bits set to zero in the `chunk_cut_fingerprint` value which successfully marked the end of a data chunk.

**Comment by green-coder** [comment]
Maybe it would be possible to have an `{objectMode: true}` for this module, with all the data of each chunk inside each object?

**Comment by max-mapper** [comment]
@green-coder sounds like a good idea. We currently use a JS array to move the offsets between C and JS, so we just need a simple way that also uses the same array to move the metadata you need. The hashing + stream API is all implemented in JS, so that part is easier to change. the `objectMode` idea would work, but i'm not sure if there is a more intuitive API. @mafintosh do you have any thoughts?

Also @green-coder to build the module, do this https://www.npmjs.com/package/node-gyp-install and then `node-gyp rebuild` to build the module

**Comment by mafintosh** [comment]
:+1: on exposing the metadata somehow. :-1: on using `objectMode` for it since thats generic a stream option. I'd be fine with some other option though like `{metadata: true}`

**Comment by green-coder** [comment]
I successfully built the module and I saw how `nan` is working for the binding. However, I would probably do a bad job doing the modifications myself because I don't know well enough the coding conventions and styles accepted by the JS community.

At my level, what I can do is to write a new version of the merkel-tree-stream which will take advantage of the chunk's metadata to group the nodes together, and publish it on Github. Hopefully, the algorithm will be useful to @mafintosh if he want to update his module.

**Comment by green-coder** [comment]
The idea of reusing the delimiter's hash for higher level nodes comes from the [design documentation of BUP](https://github.com/bup/bup/blob/master/DESIGN#L92) .

**Comment by green-coder** [comment]
Hi @mafintosh, I made an [improved version of the merkel-tree-stream](https://github.com/green-coder/merkel-stream), please let me know what you think of it.

I am looking forward for progresses on the `rabin` module so I can use it from my module on it.

**Comment by green-coder** [comment]
I am working on a PR, will submit it soon.
